
import React from 'react';
import TorrentTable from './TorrentTable';

const popularTorrents = [
  {
    id: '1',
    title: 'Dune Part Two (2024) [2160p] [4K] [BluRay] [x265]',
    category: 'Movies',
    seeds: 2451,
    leechers: 732,
    size: '28.4 GB',
    uploadDate: '16 May 2024',
    uploader: 'RARBG',
    isVerified: true,
  },
  {
    id: '2',
    title: 'Fallout Complete Season 1 [1080p] [WEB-DL] [5.1] [x264]',
    category: 'TV',
    seeds: 3218,
    leechers: 876,
    size: '16.2 GB',
    uploadDate: '15 May 2024',
    uploader: 'EZTV',
    isVerified: true,
  },
  {
    id: '3',
    title: 'Elden Ring [GOG] + All DLCs + Shadow of the Erdtree',
    category: 'Games',
    seeds: 1247,
    leechers: 532,
    size: '62.7 GB',
    uploadDate: '12 May 2024',
    uploader: 'FitGirl',
    isVerified: true,
  },
  {
    id: '4',
    title: 'Adobe Photoshop 2024 v25.8.0.427 (x64) Multilingual',
    category: 'Applications',
    seeds: 937,
    leechers: 152,
    size: '3.8 GB',
    uploadDate: '14 May 2024',
    uploader: 'm0nkrus',
    isVerified: true,
  },
  {
    id: '5',
    title: 'The Batman (2022) [1080p] [BluRay] [5.1] [YTS]',
    category: 'Movies',
    seeds: 1853,
    leechers: 421,
    size: '2.4 GB',
    uploadDate: '13 May 2024',
    uploader: 'YTS',
    isVerified: true,
  },
  {
    id: '6',
    title: 'The Bear Complete Season 2 [1080p] [WEB-DL] [H264]',
    category: 'TV',
    seeds: 1532,
    leechers: 342,
    size: '10.7 GB',
    uploadDate: '11 May 2024',
    uploader: 'EZTV',
    isVerified: true,
  },
  {
    id: '7',
    title: 'Deadpool & Wolverine (2024) [1080p] [HDTS] [C4S]',
    category: 'Movies',
    seeds: 4853,
    leechers: 1203,
    size: '2.1 GB',
    uploadDate: '15 May 2024',
    uploader: 'C4S',
    isVerified: false,
  },
  {
    id: '8',
    title: 'Windows 11 Pro 22H2 (x64) Activated [Pre-Activated]',
    category: 'Applications',
    seeds: 2145,
    leechers: 417,
    size: '4.9 GB',
    uploadDate: '10 May 2024',
    uploader: 'MrPCWarez',
    isVerified: true,
  },
  {
    id: '9',
    title: 'Oppenheimer (2023) [2160p] [4K] [HDR] [BluRay] [IMAX] [x265]',
    category: 'Movies',
    seeds: 3257,
    leechers: 498,
    size: '32.6 GB',
    uploadDate: '09 May 2024',
    uploader: 'FraMeSToR',
    isVerified: true,
  },
  {
    id: '10',
    title: 'Microsoft Office 2021 Professional Plus v2108 Build 14332.20262',
    category: 'Applications',
    seeds: 1756,
    leechers: 324,
    size: '4.2 GB',
    uploadDate: '08 May 2024',
    uploader: 'KMS_Activator',
    isVerified: true,
  },
  {
    id: '11',
    title: 'Shogun Complete Season 1 [2160p] [HDR] [WEB-DL]',
    category: 'TV',
    seeds: 3564,
    leechers: 765,
    size: '42.8 GB',
    uploadDate: '07 May 2024',
    uploader: 'FLUX',
    isVerified: true,
  },
  {
    id: '12',
    title: 'Hogwarts Legacy [FitGirl Repack] [Deluxe Edition]',
    category: 'Games',
    seeds: 2853,
    leechers: 936,
    size: '68.5 GB',
    uploadDate: '06 May 2024',
    uploader: 'FitGirl',
    isVerified: true,
  },
  {
    id: '13',
    title: 'Avengers Endgame (2019) [2160p] [4K] [HDR] [BluRay] [x265]',
    category: 'Movies',
    seeds: 1647,
    leechers: 274,
    size: '24.7 GB',
    uploadDate: '05 May 2024',
    uploader: 'RARBG',
    isVerified: true,
  },
  {
    id: '14',
    title: 'FL Studio 21.2.0 Producer Edition + All Plugins Bundle',
    category: 'Applications',
    seeds: 1423,
    leechers: 221,
    size: '12.8 GB',
    uploadDate: '04 May 2024',
    uploader: 'R2R',
    isVerified: true,
  },
  {
    id: '15',
    title: 'Silo Season 1 Complete [1080p] [WEB-DL] [x265]',
    category: 'TV',
    seeds: 2476,
    leechers: 523,
    size: '18.4 GB',
    uploadDate: '03 May 2024',
    uploader: 'EZTV',
    isVerified: true,
  },
  {
    id: '16',
    title: 'Red Dead Redemption 2 [Ultimate Edition] [GOG]',
    category: 'Games',
    seeds: 3147,
    leechers: 845,
    size: '112.3 GB',
    uploadDate: '02 May 2024',
    uploader: 'InsaneRamZes',
    isVerified: true,
  },
  {
    id: '17',
    title: 'The Lion King 4K Collection 1994-2019 [2160p] [BluRay] [x265] [HEVC]',
    category: 'Movies',
    seeds: 1842,
    leechers: 412,
    size: '78.3 GB',
    uploadDate: '01 May 2024',
    uploader: 'QxR',
    isVerified: true,
  },
  {
    id: '18',
    title: 'Cyberpunk 2077 v2.0 + Phantom Liberty [GOG]',
    category: 'Games',
    seeds: 2956,
    leechers: 689,
    size: '98.4 GB',
    uploadDate: '30 Apr 2024',
    uploader: 'FitGirl',
    isVerified: true,
  },
  {
    id: '19',
    title: 'True Detective Night Country Complete [1080p] [WEB-DL] [5.1]',
    category: 'TV',
    seeds: 1865,
    leechers: 387,
    size: '14.6 GB',
    uploadDate: '29 Apr 2024',
    uploader: 'FLUX',
    isVerified: true,
  },
  {
    id: '20',
    title: 'Star Wars The Complete Saga 1-9 [2160p] [4K] [BluRay] [x265]',
    category: 'Movies',
    seeds: 3572,
    leechers: 876,
    size: '156.7 GB',
    uploadDate: '28 Apr 2024',
    uploader: 'FraMeSToR',
    isVerified: true,
  },
];

const PopularTorrents = () => {
  return <TorrentTable torrents={popularTorrents} title="Popular Torrents" />;
};

export default PopularTorrents;
